### PR TITLE
Update to latest azure libs

### PR DESCRIPTION
**Pull request by nuwang**
xref: https://github.com/CloudVE/cloudbridge/pull/274

### CODE REVIEW

**Comment by FabioRosado** [comment]
Hello @nuwang  forgive me for sending the message here, just wanted to share my findings and prevent double effort :smile:  I was able to dig a bit more and found out why the storage account wasn't being created (at least lot of tests were failing with this error). Changing a few things and the storage account is not being created.

I am still seeing other errors like disks aren't being created and such, but doing good progress :+1:

**Comment by nuwang** [comment]
@FabioRosado Thanks for the update and for working on this and let's continue the discussion here. Great to hear that you've found out the reason for the storage account not being created and are narrowing in on the other issues.

**Comment by FabioRosado** [comment]
The permissions issue that we see when we try to create or upload an object is related to my changes so I need to dig into that as well :smile:

**Comment by nuwang** [comment]
@FabioRosado I've cleaned up the remaining issues and it's all looking good! Thanks again for all your work on this. Hoping to make a new release of cloudbridge tomorrow or so.

**Comment by FabioRosado** [comment]
This is great thank you so much for the help finishing this! Apologies for not working on the update for a while

**Comment by nuwang** [comment]
@FabioRosado New release is out: https://github.com/CloudVE/cloudbridge/releases/tag/v2.2.0

**Pull request merged**
