### PR TITLE
Filter out instance type by region.

### PR DESCRIPTION
**Pull request by nuwang**
Fixes: https://github.com/CloudVE/cloudbridge/issues/153

### CODE REVIEW

**Comment by nuwang** [comment]
There's a small issue with this fix. Some instance types in our data source does not have pricing data for certain instance_types, for example the t3 series. As a result, they are always filtered out, although us-east-1 for example, supports t3.

This is the full set of instance types that got completely filtered out in us-east-1, although I think us-east-1 supports almost all instance types. If we can live without these types altogether, this would certainly reduce issues with unsupported instance types. Eventually, the data source may get updated to include price data for this.

```
{'f1.4xlarge',
 'r5.12xlarge',
 'r5.24xlarge',
 'r5.2xlarge',
 'r5.4xlarge',
 'r5.large',
 'r5.xlarge',
 'r5d.12xlarge',
 'r5d.24xlarge',
 'r5d.2xlarge',
 'r5d.4xlarge',
 'r5d.large',
 'r5d.xlarge',
 't3.2xlarge',
 't3.large',
 't3.medium',
 't3.micro',
 't3.nano',
 't3.small',
 't3.xlarge',
 'u-12tb1.metal',
 'u-6tb1.metal',
 'u-9tb1.metal',
 'z1d.12xlarge',
 'z1d.2xlarge',
 'z1d.3xlarge',
 'z1d.6xlarge',
 'z1d.large',
 'z1d.xlarge'}
```

**Comment by afgane** [comment]
I feel t3 in particular is a popular instance type. For Galaxy, r5 is probably desirable as well so I don't really think we should be filtering those by default.

**Comment by nuwang** [comment]
In that case, the only recourse seems to be to make a PR/patch against the data source for all the instance types we need, before merging this in. I think it would be good opportunity to contribute back to that project too.

**Comment by nuwang** [comment]
Looks like it's already been worked on: https://github.com/powdahound/ec2instances.info/issues/360

**Comment by nuwang** [comment]
The missing instances have has been fixed in: https://github.com/powdahound/ec2instances.info/pull/389, so I'll go ahead and merge this.

**Pull request merged**
